### PR TITLE
Improve surefire handling

### LINKED ISSUE #24: SimpleCompiler.isSureFireBooter() returns false during tests
The surefire jar for me is called `surefire-booter` and not `surefirebooter`.

### PR DESCRIPTION
**Pull request by timowest**

### CODE REVIEW

**Comment by Shredder121** [comment]
I think it might have been a false alarm, during the test of #23 it started returning false, but it wasn't really the surefire booter, since the ClassLoader had more than one jar (so not the manifest-only jar).
Anyway, I think we can close these then.

**Comment by timowest** [comment]
Shall we still add the test case?

**Comment by Shredder121** [comment]
That actually sounds like a good idea.

**Comment by Shredder121** [comment]
It looks good to me, so we could merge it.

**Pull request merged**
